services:
  device-service-db:
    image: postgres:15-alpine
    container_name: device-service-app-db
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: device_db
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus123
    volumes:
      - device-service-db-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - sensor-network

volumes:
  device-service-db-data: {}

networks:
  sensor-network:
    driver: bridge