apiVersion: 1

datasources:
  - name: InfluxDB-SSS
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    editable: true
    jsonData:
      version: Flux
      organization: sss-quangdung
      defaultBucket: telemetry-data
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-token
    uid: influxdb-sss