services:
  auth-acl-db:
    image: postgres:15-alpine
    container_name: auth-acl-postgres-db 
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_DB: auth_acl_db
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus123
    volumes:
      - postgres_data_auth_acl_service:/var/lib/postgresql/data 
      - ./init-scripts:/docker-entrypoint-initdb.d 
    restart: unless-stopped
    networks:
      - service-network 
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data_auth_acl_service: {} 

networks:
  service-network:
    driver: bridge