services:
  # MQTT Broker - EMQX
  mqtt-broker:
    image: emqx/emqx:5.3.0
    container_name: emqx-broker
    ports:
      - "1883:1883"      # MQTT/TCP
      - "8883:8883"      # MQTT/SSL
      - "8083:8083"      # MQTT/WS
      - "8084:8084"      # MQTT/WSS
      - "18083:18083"    # Dashboard
    volumes:
      - ./emqx/etc/emqx.conf:/opt/emqx/etc/emqx.conf:ro
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log
    restart: unless-stopped
    networks:
      - sensor-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # PostgreSQL Database
  auth-acl-db:
    image: postgres:15-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: auth_acl_db
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - sensor-network

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-server
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - sensor-network
    depends_on:
      - mqtt-broker
      - auth-acl-db

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-dashboard
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - sensor-network
    depends_on:
      - prometheus

volumes:
  postgres_data:
  emqx_data:
  emqx_log:
  grafana_data:

networks:
  sensor-network:
    driver: bridge