services:
  # InfluxDB Time Series Database
  influxdb:
    image: influxdb:2.7-alpine 
    container_name: telemetry-influxdb-instance
    ports:
      - "8086:8086" 
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin 
      DOCKER_INFLUXDB_INIT_PASSWORD: password 
      DOCKER_INFLUXDB_INIT_ORG: sss-quangdung 
      DOCKER_INFLUXDB_INIT_BUCKET: telemetry-data 
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: my-super-secret-token 
    volumes:
      - influxdb_data:/var/lib/influxdb2 
    restart: unless-stopped
    networks:
      - telemetry-network 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  influxdb_data: {}

networks:
  telemetry-network:
    driver: bridge