# ./filebeat.yml
# Alternative configuration using 'container' input type

filebeat.inputs:
- type: container
  paths:
    - /var/lib/docker/containers/*/*.log
  stream: all # can be 'stdout' or 'stderr'

processors:
- add_docker_metadata: ~
- drop_event:
    when:
      equals:
        docker.container.labels.log.collection.ignore: "true"


output.logstash:
  hosts: ["logstash:5044"]
