input {
  beats {
    port => 5044
  }

  gelf {
    port => 12201
  }
}

filter {
  if [agent][type] == "filebeat" {
    mutate { add_tag => ["docker_log"] }
  } else {
    mutate { add_tag => ["quarkus_gelf"] }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logs-%{+YYYY.MM.dd}"
  }
}
