providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  mqtt:
    address: ":1883"

api:
  dashboard: true
  insecure: true

accessLog: true